title: NXTRACE REVIEW
description: "云服务器测评"
url: https://review-650.pages.dev
baseurl: ""
theme: jekyll-theme-cayman
markdown: kramdown
kramdown:
  input: GFM
permalink: pretty
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-redirect-from
defaults:
  - scope:
      path: "reviews"
    values:
      layout: default
